env:
  browser: true
  es6: true
parser: babel-eslint
extends:
  - standard
  - plugin:react/recommended
rules:
  semi:
  - 2
  - always
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
